# ============================================================
#  Calamares - Display Manager module
# ============================================================

displaymanagers:
    - sddm

basicSetup: false
sysconfigSetup: false
