# ============================================================
#  Calamares - Finished module
# ============================================================

restartNowEnabled:  true
restartNowChecked:  true
restartNowCommand:  "systemctl reboot"

notifyOnFinished: false
