# ============================================================
#  Calamares - Locale module
# ============================================================

region:   "Europe"
zone:     "Bucharest"
localeGenPath: "/etc/locale.gen"
geoipUrl: "https://geoip.kde.org/v1/calamares"
