# ============================================================
#  Calamares - Partition module
# ============================================================

efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: "300M"
efiSystemPartitionName: "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

# Default partition layout
defaultFileSystemType: "ext4"

# Minimum sizes
requiredStorage: 20

# Allow manual partitioning
allowManualPartitioning: true
