# ============================================================
#  Calamares - Unpackfs module
#  Copies the live filesystem to the target disk
# ============================================================

unpack:
    -   source: "/run/live/medium/live/filesystem.squashfs"
        sourcefs: "squashfs"
        destination: ""
