# ============================================================
#  Calamares - Users module
# ============================================================

defaultGroups:
    - name: sudo
      must_exist: true
      state: true
    - name: audio
      must_exist: false
      state: true
    - name: video
      must_exist: false
      state: true
    - name: plugdev
      must_exist: false
      state: true
    - name: netdev
      must_exist: false
      state: true
    - name: bluetooth
      must_exist: false
      state: true

autologinGroup: autologin
doAutologin:    false
sudoersGroup:   sudo

setRootPassword: true
doReusePassword: true

passwordRequirements:
    minLength: 6

allowWeakPasswords:         false
allowWeakPasswordsDefault:  false

avatarFilePath: ~/.face

userShell: /bin/bash
