# ============================================================
#  Calamares - Welcome module
# ============================================================

showSupportUrl:      true
showKnownIssuesUrl:  false
showReleaseNotesUrl: false
showDonateUrl:       false

requirements:
    check:
        - storage
        - ram
        - power
        - internet
    mandatory:
        - storage
        - ram

    requiredStorage:    20.0    # GB
    requiredRam:        2.0     # GB
    internetCheckUrl:   "https://github.com"
